### ДЗ к уроку № 7 "Введение в высшую математику"

#### Часть 1: Введение в линейную алгебру

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import scipy 
import scipy.linalg  

#### 5.1.

Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [2]:
E = np.identity(5)              # единичная матрица заданного размера
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
a = E*5
a

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [4]:
p = np.linalg.inv(a)
p

array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0. ],
       [-0. , -0. , -0. ,  0.2, -0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

#### 5.2.

Вычислите определитель:

In [5]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
round(np.linalg.det(a))

60.0

#### 5.3.1)

Вычислите матрицу, обратную данной:

In [6]:
p = np.linalg.inv(a)
p

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

#### 5.3.2)

Приведите пример матрицы 4х4, ранг которой равен 1.

In [7]:
a = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],[7, 7, 7, 7]])
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [7, 7, 7, 7]])

In [8]:
np.linalg.matrix_rank(a, 0.0001)

1

#### 5.4.

Вычислите скалярное произведение двух векторов: (1, 5)  и  (2, 8)

In [9]:
a = np.array([1, 5])
b = np.array([2, 8])
np.inner(a,b)

42

#### 5.5

Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [10]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))

228.5
228.5


#### Часть 2: Введение в высшую математику

#### 6.1 

Решите линейную систему:

In [11]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])          ### одним вариантом решения
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [12]:
A1 = np.linalg.inv(A)                                     ### другим вариантом решения
print("det =", round(np.linalg.det(A)))
np.dot(A1, B)

det = 60.0


array([-9.2       ,  0.9       ,  6.46666667])

#### 6.2

Найдите псевдорешение:

In [13]:
A = np.array([[1, 2, -1],[3, -4, 0],[8, -5, 2],[2, -5 ,0],[11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

In [14]:
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(B, 0.0001)

(3, 1)

In [15]:
np.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.15601029, -0.889718  , -0.85029782])

#### 6.3

Сколько решений имеет линейная система:

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([ 2.83726777e+16, -5.67453553e+16,  2.83726777e+16])

Получены нули. СЛАУ - несовместна.

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [17]:
A_N = np.array([[1, 3, 3], [4, 5, 6], [7, 8, 9]])
B_N = np.array([[2, 2, 1]])

In [18]:
C = np.concatenate((A_N, B_N.T), axis=1)
np.linalg.matrix_rank(A_N, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(3, 3)

In [19]:
np.linalg.det(A_N)

6.0

#### 6.4

Вычислите LU-разложение матрицы:

In [20]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

print("det =", round(np.linalg.det(A)))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
det = 432.0


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [21]:
B = np.array([8, 4, 17])
np.linalg.solve(A, B)

array([ 9.93055556, -1.17361111,  0.13888889])

#### 6.5

Найдите нормальное псевдорешение недоопределенной системы:
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [22]:
def Q(x, y, z):
    return (x**2 + y**2 + z**2)

In [23]:
A = np.array([[1, 2, -1],[8, -5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.38191882, -0.18081181,  0.0202952 ])

#### 6.6

Найдите одно из псевдорешений вырожденной системы:

In [24]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [25]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [26]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [27]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.45096256e-15])

In [28]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 9.45096256e-15 0.00000000e+00]


1.4999999999999893

In [29]:
np.linalg.norm(np.dot(A, X) - B)      # нормальное псевдорешение

1.2247448713915885